//! `cargo xtask diagram <target>` — the I/O shell around the `diagram` crate.
//! This module owns the side effects (shelling out to `cargo metadata`, reading
//! and writing `docs/generated/`, the `--check` diff); all projection logic
//! lives in `diagram` and is host-tested there. See `docs/diagrams-design.md`.

use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode};

/// The committed crate-graph artifact, relative to the workspace root.
const DEPS_DOC: &str = "docs/generated/deps.md";

/// Generate (or, with `check`, verify) the workspace crate-dependency graph.
pub fn deps(check: bool) -> ExitCode {
    let json = match cargo_metadata() {
        Ok(json) => json,
        Err(err) => {
            eprintln!("diagram deps: {err}");
            return ExitCode::from(1);
        }
    };
    let members = match diagram::deps::parse_cargo_metadata(&json) {
        Ok(members) => members,
        Err(err) => {
            eprintln!("diagram deps: parsing cargo metadata: {err}");
            return ExitCode::from(1);
        }
    };
    let mermaid = diagram::deps::workspace_graph(&members).to_mermaid();
    let doc = render_doc("Workspace crate graph", "deps", &mermaid);

    let path = workspace_root().join(DEPS_DOC);
    if check {
        check_up_to_date(&path, &doc, "deps")
    } else {
        write_doc(&path, &doc)
    }
}

/// `cargo metadata --no-deps` — packages are exactly the workspace members,
/// each still listing its declared dependency names.
fn cargo_metadata() -> Result<String, String> {
    let out = Command::new("cargo")
        .args(["metadata", "--format-version", "1", "--no-deps"])
        .output()
        .map_err(|e| format!("failed to invoke cargo metadata: {e}"))?;
    if !out.status.success() {
        return Err(format!("cargo metadata failed: {}", String::from_utf8_lossy(&out.stderr)));
    }
    String::from_utf8(out.stdout).map_err(|e| format!("cargo metadata output not utf-8: {e}"))
}

/// Wrap the mermaid body in the generated-doc envelope: a provenance header so
/// nobody hand-edits it, a title, and a fenced ` ```mermaid ` block GitHub
/// renders in-diff.
fn render_doc(title: &str, target: &str, mermaid: &str) -> String {
    format!(
        "<!-- generated by: cargo xtask diagram {target} — do not edit -->\n\n\
         # {title}\n\n\
         ```mermaid\n{mermaid}```\n"
    )
}

fn write_doc(path: &Path, doc: &str) -> ExitCode {
    if let Some(parent) = path.parent() {
        if let Err(e) = std::fs::create_dir_all(parent) {
            eprintln!("diagram: creating {}: {e}", parent.display());
            return ExitCode::from(1);
        }
    }
    match std::fs::write(path, doc) {
        Ok(()) => {
            eprintln!("diagram: wrote {}", path.display());
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("diagram: writing {}: {e}", path.display());
            ExitCode::from(1)
        }
    }
}

fn check_up_to_date(path: &Path, expected: &str, target: &str) -> ExitCode {
    let actual = std::fs::read_to_string(path).unwrap_or_default();
    if actual == expected {
        eprintln!("diagram {target}: {} is up to date", path.display());
        ExitCode::SUCCESS
    } else {
        eprintln!(
            "diagram {target}: {} is stale — regenerate with `cargo xtask diagram {target}`",
            path.display()
        );
        ExitCode::from(1)
    }
}

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask has a workspace-root parent")
        .to_path_buf()
}
