//! `cargo xtask diagram <target>` — the I/O shell around the `diagram` crate.
//! This module owns the side effects (shelling out to `cargo metadata`, reading
//! and writing `docs/generated/`, the `--check` diff); all projection logic
//! lives in `diagram` and is host-tested there. See `docs/diagrams-design.md`.

use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode, Stdio};

/// The committed crate-graph artifact, relative to the workspace root.
const DEPS_DOC: &str = "docs/generated/deps.md";

/// Verify every committed diagram in `docs/generated/` is up to date. Called
/// from the `cargo xtask test` gate so a stale diagram fails the suite. New
/// generated targets add their `--check` here.
pub fn check_all() -> ExitCode {
    deps(true)
}

/// Generate (or, with `check`, verify) the workspace crate-dependency graph.
pub fn deps(check: bool) -> ExitCode {
    let json = match cargo_metadata() {
        Ok(json) => json,
        Err(err) => {
            eprintln!("diagram deps: {err}");
            return ExitCode::from(1);
        }
    };
    let members = match diagram::deps::parse_cargo_metadata(&json) {
        Ok(members) => members,
        Err(err) => {
            eprintln!("diagram deps: parsing cargo metadata: {err}");
            return ExitCode::from(1);
        }
    };
    let graph = diagram::deps::workspace_graph(&members);
    let doc = render_doc("Workspace crate graph", "deps", &graph.to_mermaid());

    let path = workspace_root().join(DEPS_DOC);
    if check {
        return check_up_to_date(&path, &doc, "deps");
    }
    let written = write_doc(&path, &doc);
    if written != ExitCode::SUCCESS {
        return written;
    }
    // Local-dev convenience: also render an SVG via graphviz. Best-effort —
    // the committed, reviewable source of truth is the mermaid .md; a missing
    // `dot` never fails the command.
    render_svg(&graph.to_dot(), &path.with_extension("svg"));
    ExitCode::SUCCESS
}

/// Pipe DOT to `dot -Tsvg`, writing an SVG next to the `.md`. Graphviz layout
/// is version-dependent, so this artifact is gitignored (not `--check`ed);
/// it's just something to open in a browser during local dev. Absent `dot`,
/// warn and carry on.
fn render_svg(dot: &str, out: &Path) {
    let Ok(mut child) = Command::new("dot")
        .args(["-Tsvg", "-o"])
        .arg(out)
        .stdin(Stdio::piped())
        .spawn()
    else {
        eprintln!(
            "diagram: `dot` not found — skipping SVG (install graphviz, e.g. \
             `brew install graphviz`); the mermaid .md is written regardless"
        );
        return;
    };
    if let Some(mut stdin) = child.stdin.take()
        && let Err(e) = stdin.write_all(dot.as_bytes())
    {
        eprintln!("diagram: writing to dot: {e}");
        return;
    }
    match child.wait() {
        Ok(status) if status.success() => eprintln!("diagram: wrote {}", out.display()),
        Ok(status) => eprintln!("diagram: dot exited with {status}"),
        Err(e) => eprintln!("diagram: waiting on dot: {e}"),
    }
}

/// `cargo metadata --no-deps` — packages are exactly the workspace members,
/// each still listing its declared dependency names.
fn cargo_metadata() -> Result<String, String> {
    let out = Command::new("cargo")
        .args(["metadata", "--format-version", "1", "--no-deps"])
        .output()
        .map_err(|e| format!("failed to invoke cargo metadata: {e}"))?;
    if !out.status.success() {
        return Err(format!("cargo metadata failed: {}", String::from_utf8_lossy(&out.stderr)));
    }
    String::from_utf8(out.stdout).map_err(|e| format!("cargo metadata output not utf-8: {e}"))
}

/// Wrap the mermaid body in the generated-doc envelope: a provenance header so
/// nobody hand-edits it, a title, and a fenced ` ```mermaid ` block GitHub
/// renders in-diff.
fn render_doc(title: &str, target: &str, mermaid: &str) -> String {
    format!(
        "<!-- generated by: cargo xtask diagram {target} — do not edit -->\n\n\
         # {title}\n\n\
         ```mermaid\n{mermaid}```\n"
    )
}

fn write_doc(path: &Path, doc: &str) -> ExitCode {
    if let Some(parent) = path.parent()
        && let Err(e) = std::fs::create_dir_all(parent)
    {
        eprintln!("diagram: creating {}: {e}", parent.display());
        return ExitCode::from(1);
    }
    match std::fs::write(path, doc) {
        Ok(()) => {
            eprintln!("diagram: wrote {}", path.display());
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("diagram: writing {}: {e}", path.display());
            ExitCode::from(1)
        }
    }
}

fn check_up_to_date(path: &Path, expected: &str, target: &str) -> ExitCode {
    let actual = std::fs::read_to_string(path).unwrap_or_default();
    if actual == expected {
        eprintln!("diagram {target}: {} is up to date", path.display());
        ExitCode::SUCCESS
    } else {
        eprintln!(
            "diagram {target}: {} is stale — regenerate with `cargo xtask diagram {target}`",
            path.display()
        );
        ExitCode::from(1)
    }
}

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask has a workspace-root parent")
        .to_path_buf()
}
